spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boki_test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
#  jpa:
#    properties:
#      hibernate:
#        jdbc:
#          time_zone: Asia/Seoul
#        default_batch_fetch_size: 100
#      show_sql: true
#      format_sql: true
#      highlight_sql: true
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create
#  sql:
#    init:
#            mode: always
#      mode: always
#  web:
#    resources:
#      add-mappings: false
logging:
#  level:
#    root: info
  pattern:
    level:
      org.hibernate.orm.jdbc.bind: trace
#    org.hibernate: debug